### ISSUE TITLE
HI, old friend

### ISSUE THREAD

**Issue by jiyuuni** [akw28888/trackerlist#1]
akw大佬安安，還記得我ㄇ🥺🥺🥺

**Comment by jason-akw** [comment]
好久不見欸

**Comment by jiyuuni** [comment]
你還願意回覆我哦TT，前幾天查XGPON看到你M01還有在活動。
你有TG還DC或其他聯絡方式嗎?我QQ登不進去了...

**Comment by jason-akw** [comment]
TG DC都有
但我TG沒username

可以去 @twnog 找我
